image_downloader:
  build: image_downloader
  volumes:
    - /opt/watadare/image:/app/image

index_builder:
  build: index_builder
  volumes:
    - /opt/watadare/image:/app/image

search_api:
  build: search_api
  volumes:
    - /opt/watadare/image:/app/image
