image_downloader:
  build: image_downloader
  volumes:
    - /opt/watadare/image:/app/image
  environment:
    - QUERY=芸能人
    - SAVE_DIRECTORY=image
    - IMAGE_TIMESTAMP_PATH=image.timestamp

index_builder:
  build: index_builder
  volumes:
    - /opt/watadare/image:/app/image
    - /opt/watadare/db:/app/db
  environment:
    - IMAGE_PATH=image
    - IMAGE_TIMESTAMP_PATH=image.timestamp
    - DB_PATH=db
    - DB_TIMESTAMP_PATH=db.timestamp

search_api:
  build: search_api
  volumes:
    - /opt/watadare/image:/app/static/image
    - /opt/watadare/db:/app/db
  ports:
    - 8080:8080
  environment:
    - DB_TIMESTAMP_PATH=db.timestamp
    - DB_FILE_PATH=db/db.txt
