image_downloader:
  build: image_downloader
  volumes:
    - /opt/watadare/image:/app/image

index_builder:
  build: index_builder
  volumes:
    - /opt/watadare/image:/app/image
    - /opt/watadare/db:/app/db

search_api:
  build: search_api
  volumes:
    - /opt/watadare/image:/app/static/image
    - /opt/watadare/db:/app/db
  ports:
    - 8080:8080
