image_downloader:
  build: image_downloader
  volumes:
    - /opt/watadare:/app/

index_builder:
  build: index_builder
  volumes:
    - /opt/watadare:/app/

search_api:
  build: search_api
  volumes:
    - /opt/watadare/:/app/
